version: '3.4'

services:
  cluster:
    image: grokzen/redis-cluster:6.2.1
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
    environment:
      IP: 0.0.0.0
      INITIAL_PORT: 7000

  redis:
    image: redis:7
    ports:
      - "6379:6379"
